### ISSUE TITLE
Couldn't find a tree builder with the features you requested: lxml

### ISSUE THREAD

**Issue by c-z-chen** [saleguas/PastPapersDownloader#1]
Hi! I wanted to download all IGCSE past papers (only maths actually but I do not imagine this tool can do categorisation), yet it reports me the following:

```
➜  ppdr git:(master) ✗ python main.py -I ALL
Fetching Exam links...
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from scripts import parser
  File "/Users/admin/projects/ppdr/scripts/parser.py", line 34, in <module>
    mainMethods.downloadIGCSE(args['IGCSE'])
  File "./scripts/mainMethods.py", line 75, in downloadIGCSE
    RemoteLinks.IGCSE.value, syllabusCode)
  File "./scripts/mainMethods.py", line 45, in downloadCAIE
    examClasses = web_data.getExamClasses(url, pattern)
  File "./scripts/web_data.py", line 20, in getExamClasses
    soup = BeautifulSoup(page, "lxml")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bs4/__init__.py", line 246, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

I am really noob to all these python stuff as I do front-end dev, so can you help me a bit with this?

---

I am using:
- macOS Mojave
- python 3.7.4

I have `pip install`ed `bs4` and `requests` as requested in tracebacks before.

**Comment by abdullah-arham** [comment]
Try running `pip install lxml`

**Comment by BEFOR3SH0CK** [comment]
pip install requests
pip install bs4
pip install lxml

This project is probably no longer maintained. It's outdated and likely relies on an outdated version of the PapaCambridge site with a different structure so that is probably why it no longer works.
